language: node_js
sudo: false

node_js:
  - '4'

env:
  global:
    # get the latest code from master
    - SENECA_VER=mihaidma/seneca
    # to clone a specific tagged version set the version like the following:
    # - SENECA_VER=senecajs/seneca#v1.3.0

  matrix:
    # plugins to test
   - TEST_SUITE=senecajs/gate-executor
   - TEST_SUITE=senecajs/ramanujan
   - TEST_SUITE=senecajs/seneca-auth
   - TEST_SUITE=senecajs/seneca-balance-client
   - TEST_SUITE=senecajs/seneca-basic
   - TEST_SUITE=senecajs/seneca-cache
   - TEST_SUITE=senecajs/seneca-cache-test
   - TEST_SUITE=senecajs/seneca-entity
   - TEST_SUITE=senecajs/seneca-jsonfile-store
   - TEST_SUITE=senecajs/seneca-level-store
   - TEST_SUITE=senecajs/seneca-mem-store
   - TEST_SUITE=senecajs/seneca-mesh
   - TEST_SUITE=senecajs/seneca-mongo-store
   # - TEST_SUITE=senecajs/seneca-mvp
   #ok - TEST_SUITE=senecajs/seneca-mysql-store
   #ok - TEST_SUITE=senecajs/seneca-postgres-store
   - TEST_SUITE=senecajs/seneca-rabbitmq-transport
   - TEST_SUITE=senecajs/seneca-redis-cache
   - TEST_SUITE=senecajs/seneca-redis-queue-transport
   #ok - TEST_SUITE=senecajs/seneca-redis-store
   - TEST_SUITE=senecajs/seneca-registry
   - TEST_SUITE=senecajs/seneca-repl
   - TEST_SUITE=senecajs/seneca-store-test
   - TEST_SUITE=senecajs/seneca-transport
   # - TEST_SUITE=senecajs/seneca-transport-test
   - TEST_SUITE=senecajs/seneca-user
   - TEST_SUITE=senecajs/seneca-web

#    - TEST_SUITE=senecajs/seneca

before_script:
  - if [[ $TRAVIS_NODE_VERSION == "6" ]]; then export LAB_FLAGS="--leaks"; else export LAB_FLAGS=""; fi
  - TEST_SUITE_FOLDER=$(basename $TEST_SUITE)
  - echo LAB_FLAGS:$LAB_FLAGS
  - echo TEST_SUITE:$TEST_SUITE
  - echo TEST_SUITE_FOLDER:$TEST_SUITE_FOLDER
  - if [ $TEST_SUITE_FOLDER != 'seneca' ]; then
      git clone https://github.com/$TEST_SUITE;
      cd $TEST_SUITE_FOLDER;
      npm i;
      npm uninstall seneca;
      npm install https://github.com/$SENECA_VER;
    fi
  - if [ $TEST_SUITE_FOLDER = 'seneca-postgres-store' ]; then psql -U postgres -f ./docker/dbschema.sql ; fi
  - if [ $TEST_SUITE_FOLDER = 'seneca-mysql-store' ]; then mysql -h localhost -u root --password="" < ./script/schema.sql ; fi

cache:
  directories:
  - node_modules

addons:
  postgresql: "9.4"

services:
  - postgresql
  - mysql
  - redis-server
  - mongodb
  - rabbitmq
