language: node_js
sudo: required
dist: trusty
cache: false

node_js:
  - '6'
  - '4'

env:
  global:
    # get the latest code from master
    - SENECA_VER=senecajs/seneca#seneca3
    # to clone a specific tagged version set the version like the following:
    # - SENECA_VER=senecajs/seneca#v1.3.0

  matrix:
    # plugins to test
    #- TEST_SUITE=senecajs/seneca
    - TEST_SUITE=senecajs/gate-executor
    - TEST_SUITE=senecajs/seneca-parambulator
    - TEST_SUITE=senecajs/seneca-basic
    - TEST_SUITE=senecajs/seneca-repl
    - TEST_SUITE=senecajs/seneca-entity
    - TEST_SUITE=senecajs/seneca-store-test
    - TEST_SUITE=senecajs/seneca-jsonfile-store
    - TEST_SUITE=senecajs/seneca-level-store
    - TEST_SUITE=senecajs/seneca-mem-store
    - TEST_SUITE=senecajs/seneca-mongo-store
    - TEST_SUITE=senecajs/seneca-redis-store
    - TEST_SUITE=senecajs/seneca-mysql-store
    - TEST_SUITE=senecajs/seneca-postgres-store
    - TEST_SUITE=senecajs/seneca-transport-test
    - TEST_SUITE=senecajs/seneca-transport
    - TEST_SUITE=senecajs/seneca-redis-queue-transport
    - TEST_SUITE=senecajs/seneca-redis-pubsub-transport
    - TEST_SUITE=senecajs/seneca-balance-client
    - TEST_SUITE=senecajs/seneca-registry
    - TEST_SUITE=senecajs/seneca-mesh
    - TEST_SUITE=senecajs/seneca-user
    - TEST_SUITE=senecajs/seneca-web
    - TEST_SUITE=senecajs/seneca-auth
    - TEST_SUITE=senecajs/seneca-logstash-logger
    - TEST_SUITE=senecajs/seneca-pino-logger
    - TEST_SUITE=senecajs/seneca-logentries-logger
    - TEST_SUITE=senecajs/seneca-joi
    - TEST_SUITE=senecajs/seneca-beanstalk-transport


before_script:
  - echo SENECA_VER:$SENECA_VER
  - TEST_SUITE_FOLDER=$(basename $TEST_SUITE)
  - echo TEST_SUITE:$TEST_SUITE
  - echo TEST_SUITE_FOLDER:$TEST_SUITE_FOLDER
  - if [ $TEST_SUITE_FOLDER != 'seneca' ]; then
      git clone https://github.com/$TEST_SUITE;
      cd $TEST_SUITE_FOLDER;
      npm i;
      npm uninstall seneca;
      npm install https://github.com/$SENECA_VER;
    fi
  - if [ $TEST_SUITE_FOLDER = 'seneca-postgres-store' ]; then psql -U postgres -f ./docker/dbschema.sql ; fi
  - if [ $TEST_SUITE_FOLDER = 'seneca-mysql-store' ]; then mysql -h localhost -u root --password="" < ./script/schema.sql ; fi

addons:
  postgresql: "9.4"

services:
  - postgresql
  - mysql
  - redis-server
  - mongodb

